name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sambit-rgb_Java-juliet-test-suite
            -Dsonar.organization=sambit-rgb
            -Dsonar.sources=.
            -Dsonar.exclusions=**/testcases/**,**/*ServletMain.java
            -Dsonar.java.binaries=.
            -Dsonar.host.url=https://sonarcloud.io
